foodgram/urls.py
from django.conf.urls import handler404, handler500  # noqa
from django.contrib import admin
from django.urls import include, path

from foodgram.views import AboutAuthorView, AboutTechView

urlpatterns = [
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('about/author/', AboutAuthorView.as_view(), name='about-author'),
    path('about/technology/', AboutTechView.as_view(), name='about-tech'),
    path('', include('recipes.urls')),
]

handler404 = 'foodgram.views.page_not_found' # noqa
handler500 = 'foodgram.views.server_error' # noqa

recipes/urls.py
from django.urls import path

from .views import (add_favorite, add_purchase, add_subscription,
                    delete_favorite, delete_purchase, delete_recipe,
                    delete_subscription, download_pdf, edit_recipe,
                    favorite_index, follow_index, get_ingredients, index,
                    new_recipe, profile, purchases, recipe_detail)

urlpatterns = [
    path('', index, name='index'),
    path('recipes/<int:recipe_id>/', recipe_detail, name='recipe'),
    path('recipes/<int:recipe_id>/edit/', edit_recipe, name='edit_recipe'),
    path('recipes/<int:recipe_id>/delete/', delete_recipe, name='delete_recipe'),
    path('users/<int:user_id>/', profile, name='profile'),
    path('follows/', follow_index, name='follows'),
    path('subscriptions/', add_subscription, name='subscription'),
    path('subscriptions/<int:author_id>/', delete_subscription,
         name='delete_subscription'),
    path('favorites/', favorite_index, name='favorite'),
    path('add-favorite/', add_favorite, name='add_favorite'),
    path('del-favorite/<int:recipe_id>/', delete_favorite, name='del-favorite'),
    path('purchases/', purchases, name='purchases'),
    path('add-purchase/', add_purchase, name='add-purchase'),
    path('del-purchase/<int:recipe_id>/', delete_purchase, name='del-purchase'),
    path('ingredients', get_ingredients, name='ingredients'),
    path('new/', new_recipe, name='new'),
    path('download_shoplist/', download_pdf, name='download_purchases'),
]

users/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup')
]

recipes/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Tag(models.Model):
    title = models.CharField(max_length=50)
    slug = models.SlugField(unique=True)

    class Meta:
        verbose_name_plural = 'Теги'
        verbose_name = 'Теги'

    def __str__(self):
        return self.title


class Product(models.Model):
    title = models.CharField(max_length=100)
    unit = models.CharField(max_length=10)

    class Meta:
        verbose_name_plural = 'Ингредиенты'
        verbose_name = 'Ингредиенты'

    def __str__(self):
        return f'{self.title}, {self.unit}'


class Follow(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE,
                             related_name='follower',
                             help_text='Подписчик')
    author = models.ForeignKey(User, on_delete=models.CASCADE,
                               related_name='following',
                               help_text='Автор')

    class Meta:
        db_table = 'posts_follow'
        verbose_name_plural = 'Подписки'
        verbose_name = 'Подписки'
        constraints = [models.UniqueConstraint(fields=["user", "author"],
                                               name="follow_unique")]

    def __str__(self):
        return f'{self.author}'


class Recipe(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE,
                               related_name='recipes')
    title = models.CharField(max_length=50)
    image = models.ImageField(upload_to='recipes/', blank=True, null=True)
    description = models.TextField()
    ingredients = models.ManyToManyField(Product, through='Ingredient',
                                         related_name='recipes', blank=True)
    tags = models.ManyToManyField(Tag, blank=True, related_name='recipes')
    time = models.PositiveIntegerField()
    pub_date = models.DateTimeField('Дата публикации', auto_now_add=True)
    favorite_by = models.ManyToManyField(User, through='Favourite',
                                         related_name='favorite_recipes',
                                         blank=True)
    purchase_by = models.ManyToManyField(User, through='ShopList',
                                         related_name='shop_list',
                                         blank=True)

    class Meta:
        ordering = ['-pub_date']
        verbose_name_plural = 'Рецепты'
        verbose_name = 'Рецепты'

    def __str__(self):
        return f'{self.title}'


class Ingredient(models.Model):
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)
    ingredient = models.ForeignKey(Product, on_delete=models.CASCADE)
    amount = models.PositiveIntegerField()

    class Meta:
        verbose_name_plural = 'Продукты'
        verbose_name = 'Продукты'


    def __str__(self):
        return f'{self.amount}'


class Favourite(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)
    created = models.DateTimeField('date published', auto_now_add=True)

    class Meta:
        ordering = ['-created']
        verbose_name_plural = 'Избранное'
        verbose_name = 'Избранное'

    def __str__(self):
        return f'{self.recipe}'


class ShopList(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)
    created = models.DateTimeField('date of creation', auto_now_add=True)

    class Meta:
        ordering = ['-created']
        verbose_name_plural = 'Список покупок'
        verbose_name = 'Список покупок'

    def __str__(self):
        return f'{self.recipe}'

recipes/views.py
import json
from urllib.parse import unquote

import reportlab
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.http import HttpResponse, JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.http import (require_GET, require_http_methods,
                                          require_POST)
from reportlab.lib.pagesizes import A4
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfgen import canvas

from foodgram.settings import PAGINATE_BY

from .forms import RecipeForm
from .models import (Favourite, Follow, Ingredient, Product, Recipe, ShopList,
                     Tag, User)
from .utils import add_subscription_status, extend_context, tag_filter


@require_GET
def index(request):
    tags = request.GET.getlist('tag')
    recipe_list = tag_filter(Recipe, tags)
    paginator = Paginator(recipe_list, PAGINATE_BY)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    context = {
        'tags': Tag.objects.all(),
        'page': page,
        'paginator': paginator
    }
    user = request.user
    if user.is_authenticated:
        context['active'] = 'recipe'
        extend_context(context, user)
    return render(request, 'index.html', context)


@require_GET
def recipe_detail(request, recipe_id):
    recipe = get_object_or_404(Recipe, id=recipe_id)
    context = {
        'recipe': recipe,
    }
    user = request.user
    if user.is_authenticated:
        add_subscription_status(context, user, recipe.author)
        extend_context(context, user)
    return render(request, 'recipes/recipe_detail.html', context)


@require_GET
def profile(request, user_id):
    author = get_object_or_404(User, id=user_id)
    tags = request.GET.getlist('tag')
    recipe_list = tag_filter(Recipe, tags)
    paginator = Paginator(recipe_list.filter(author=author), PAGINATE_BY)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    context = {
        'tags': Tag.objects.all(),
        'author': author,
        'page': page,
        'paginator': paginator
    }
    user = request.user
    if user.is_authenticated:
        add_subscription_status(context, user, author)
        extend_context(context, user)
    return render(request, 'recipes/profile.html', context)


@login_required(login_url='/auth/login/')
def follow_index(request):
    queryset = request.user.follower.all()
    paginator = Paginator(queryset, PAGINATE_BY)
    page_number = request.GET.get("page")
    page = paginator.get_page(page_number)
    return render(request,
                  "recipes/follow.html",
                  {"page": page,
                   "paginator": paginator,
                   "page_number": page_number})


@login_required(login_url='auth/login/')
@require_POST
def add_subscription(request):
    json_data = json.loads(request.body.decode())
    author_id = json_data.get('id')
    if not author_id:
        return JsonResponse({'success': 'false', 'massage': 'id not found'},
                            status=400)
    author = get_object_or_404(User, id=author_id)
    follow = Follow.objects.filter(user=request.user, author=author)
    data = {'success': 'true'}
    if follow.exists():
        data['success'] = 'false'
    else:
        Follow.objects.create(user=request.user, author=author)
    return JsonResponse(data)


@login_required(login_url='auth/login/')
@require_http_methods('DELETE')
def delete_subscription(request, author_id):
    author = get_object_or_404(User, id=author_id)
    data = {'success': 'true'}
    follow = Follow.objects.filter(
        user=request.user, author=author)
    if not follow.exists():
        data['success'] = 'false'
    follow.delete()
    return JsonResponse(data)


@login_required(login_url='/auth/login/')
def favorite_index(request):
    tags = request.GET.getlist('tag')
    user = request.user
    recipe_lists = user.favorite_recipes.all()
    if tags:
        recipe_list = recipe_lists.prefetch_related(
            'author', 'tags'
        ).filter(
            tags__slug__in=tags
        ).distinct()
    else:
        recipe_list = recipe_lists.prefetch_related(
            'author', 'tags'
        ).all()
    paginator = Paginator(recipe_list, PAGINATE_BY)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    context = {
        'tags': Tag.objects.all(),
        'page': page,
        'paginator': paginator
    }
    if user.is_authenticated:
        extend_context(context, user)
    return render(request, 'recipes/favorites.html', context)


@login_required(login_url='auth/login/')
@require_POST
def add_favorite(request):
    json_data = json.loads(request.body.decode())
    recipe_id = json_data.get('id')
    if not recipe_id:
        return JsonResponse({'success': 'false', 'massage': 'id not found'},
                            status=400)
    recipe = get_object_or_404(Recipe, id=recipe_id)
    data = {'success': 'true'}
    favorite = Favourite.objects.filter(user=request.user, recipe=recipe)
    if favorite.exists():
        data['success'] = 'false'
    else:
        Favourite.objects.create(user=request.user, recipe=recipe)
    return JsonResponse(data)


@login_required(login_url='auth/login/')
@require_http_methods('DELETE')
def delete_favorite(request, recipe_id):
    recipe = get_object_or_404(Recipe, id=recipe_id)
    data = {'success': 'true'}
    favorite = Favourite.objects.filter(user=request.user, recipe=recipe)
    if not favorite.exists():
        data['success'] = 'false'
    favorite.delete()
    return JsonResponse(data)


@login_required(login_url='/auth/login/')
def purchases(request):
    user = request.user
    recipes = user.shop_list.all()
    return render(request, "recipes/purchases.html", {"page": recipes})


@login_required(login_url='auth/login/')
@require_POST
def add_purchase(request):
    json_data = json.loads(request.body.decode())
    recipe_id = json_data.get('id')
    if not recipe_id:
        return JsonResponse({'success': 'false', 'massage': 'id not found'},
                            status=400)
    recipe = get_object_or_404(Recipe, id=recipe_id)
    data = {'success': 'true'}
    purchase = ShopList.objects.filter(user=request.user, recipe=recipe)
    if purchase.exists():
        data['success'] = 'false'
    else:
        ShopList.objects.create(user=request.user, recipe=recipe)
    return JsonResponse(data)


@login_required(login_url='auth/login/')
@require_http_methods('DELETE')
def delete_purchase(request, recipe_id):
    recipe = get_object_or_404(Recipe, id=recipe_id)
    data = {'success': 'true'}
    purchase = ShopList.objects.filter(user=request.user, recipe=recipe)
    if not purchase.exists():
        data['success'] = 'false'
    purchase.delete()
    return JsonResponse(data)


@login_required(login_url='auth/login/')
@require_GET
def get_ingredients(request):
    query = unquote(request.GET.get('query'))
    data = list(Product.objects.filter(
        title__startswith=query
    ).values(
        'title', 'unit'))
    return JsonResponse(data, safe=False)


@login_required(login_url='/auth/login/')
@require_http_methods(['GET', 'POST'])
def new_recipe(request):
    form = RecipeForm(request.POST or None, files=request.FILES or None,
                      initial={'author': request.user})
    if form.is_valid():
        form.save()
        return redirect('index')
    return render(request, 'recipes/recipe_new.html', {'form': form})



@login_required(login_url='/auth/login/')
def edit_recipe(request, recipe_id):
    recipe = get_object_or_404(Recipe, id=recipe_id)
    if recipe.author != request.user:
        return redirect('recipe', id=recipe_id)
    form = RecipeForm(request.POST or None, files=request.FILES or None,
                      instance=recipe, initial={'author': request.user})
    tags = recipe.tags.all()
    ingredients = Ingredient.objects.filter(recipe=recipe).all()
    context = {'form': form,
               'is_created': True,
               'recipe_id': recipe.id,
               'tags': tags,
               'ingredients': ingredients}
    if form.is_valid():
        form.save()
        return redirect('recipe', recipe.id)
    return render(request, 'recipes/recipe_new.html', context)


@login_required(login_url='/auth/login/')
@require_GET
def delete_recipe(request, recipe_id):
    recipe = get_object_or_404(Recipe, id=recipe_id)
    if recipe.author == request.user:
        recipe.delete()
    return redirect('index')


@login_required
def download_pdf(request):
    reportlab.rl_config.TTFSearchPath.append(
        str(settings.BASE_DIR) + "/Library/Fonts/"
    )
    user = get_object_or_404(User, username=request.user)
    ing_dict = {}
    shop_list = ShopList.objects.filter(user=user)
    if shop_list.count() == 0:
        return redirect('purchases')
    for el in shop_list:
        ingredients = Ingredient.objects.filter(recipe=el.recipe.id)
        for ingredient in ingredients:
            name = ingredient.ingredient.title
            count = ingredient.amount
            dimension = ingredient.ingredient.unit
            if name not in ing_dict:
                ing_dict[name] = [count, dimension]
            else:
                ing_dict[name][0] += count
    response = HttpResponse(content_type="application/pdf")
    response["Content-Disposition"] = 'attachment; filename="shopList.pdf"'
    p = canvas.Canvas(response, pagesize=A4)
    pdfmetrics.registerFont(TTFont("Arial", "arial.ttf"))
    p.setFont("Arial", 20)
    x = 50
    y = 750
    for num, el in enumerate(ing_dict):
        if y <= 100:
            y = 700
            p.showPage()
            p.setFont("Arial", 20)
        p.drawString(
            x, y, f"№{num + 1}: {el} - {ing_dict[el][0]} {ing_dict[el][1]}"
        )

recipes/templates/recipes/favorites.html
{% extends 'base.html' %}
{% block title %}Избранное{% endblock %}

{% block styles %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'pages/index.css' %}">
{% endblock %}

{% block content %}
        <div class="main__header">
            <h1 class="main__title">Избранное</h1>
            {% include 'includes/tags.html' %}
        </div>
        <div class="card-list">
            {% for card in page %}
                {% include 'recipes/recipe_cards.html' with card=card favorites=page %}
            {% endfor %}
        </div>
        {% include 'includes/paginator.html' with page=page paginator=paginator %}
{% endblock %}

{% block javascript %}
    {% load static %}
    <script src="{% static 'js/components/MainCards.js' %}"></script>
    <script src="{% static 'js/components/Purchases.js' %}"></script>
    <script src="{% static 'js/components/Favorites.js' %}"></script>
    <script src="{% static 'js/config/config.js' %}"></script>
    <script src="{% static 'js/components/CardList.js' %}"></script>
    <script src="{% static 'js/components/Header.js' %}"></script>
    <script src="{% static 'js/api/Api.js' %}"></script>
    <script src="{% static 'js/favorite.js' %}"></script>
{% endblock %}

recipes/templates/recipes/follow.html
{% extends 'base.html' %}
{% block title %}Мои подписки{% endblock %}

{% block styles %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'pages/myFollow.css' %}">
{% endblock %}

{% block content %}
{% csrf_token %}
    <div class="main__header">
        <h1 class="main__title">Мои подписки</h1>
    </div>
    <div class="card-list">
        {% for card in page %}
            {% load thumbnail user_filters %}
            <div class="card-user" data-author="{{ card.author.id }}">
                <div class="card-user__header">
                    <h2 class="card-user__title"> <a href="{% url 'profile' user_id=card.author.id %}">{% if card.author.get_full_name %}{{ card.author.get_full_name }}{% else %} {{card.author}} {% endif %}</a></h2>
                </div>
                <div class="card-user__body">
                    <ul class="card-user__items">
                        {% for recipe in card.author.recipes.all %}
                            {% if forloop.counter < 4 %}
                                <li class="card-user__item">
                                    <div class="recipe">
                                        {% thumbnail recipe.image "72x72" crop="center" upscale=True as im %}
                                        <img src="{{ im.url }}" alt="{{ recipe.name }}" class="recipe__image">
                                        {% endthumbnail %}
                                        <h3 class="recipe__title">{{ recipe.title }}</h3>
                                        <p class="recipe__text"><span class="icon-time"></span> {{ recipe.time }} мин.</p>
                                    </div>
                                </li>
                            {% endif %}
                        {% endfor %}
                        <li class="card-user__item">
                            <a href="{% url 'profile' user_id=card.author.id %}" class="card-user__link link">{% if card.author.recipes.count > 3 %}Еще {{card.author.recipes.count|add:"-3"}} рецептов...{% endif %}</a>
                        </li>
                    </ul>
                </div>
                <div class="card-user__footer">
                    <button class="button button_style_light-blue button_size_auto" name="subscribe">Отписаться</button>
                </div>
            </div>
        {% endfor %}
    </div>
    {% include 'includes/paginator.html' with page=page paginator=paginator %}
{% endblock %}

{% block javascript %}
    {% load static %}
    <script src="{% static 'js/components/MainCards.js' %}"></script>
    <script src="{% static 'js/components/MyFollow.js' %}"></script>
    <script src="{% static 'js/components/Subscribe.js' %}"></script>
    <script src="{% static 'js/components/Header.js' %}"></script>
    <script src="{% static 'js/api/Api.js' %}"></script>
    <script src="{% static 'js/myFollow.js' %}"></script>
{% endblock %}

recipes/templates/recipes/follow_card.html
{% load thumbnail user_filters %}
<div class="card-user" data-author="{{ card.author.id }}">
    <div class="card-user__header">
        <h2 class="card-user__title">{% if card.author.get_full_name %}{{ card.author.get_full_name }}{% else %} {{card.author}} {% endif %}</h2>
    </div>
    <div class="card-user__body">
        <ul class="card-user__items">
            {% for recipe in card.author.recipe.all %}
                {% if forloop.counter < 4 %}
                    <li class="card-user__item">
                        <div class="recipe">
                            {% thumbnail recipe.image "72x72" crop="center" upscale=True as im %}
                            <img src="{{ im.url }}" alt="{{ recipe.name }}" class="recipe__image">
                            {% endthumbnail %}
                            <h3 class="recipe__title">{{ recipe.title }}</h3>
                            <p class="recipe__text"><span class="icon-time"></span> {{ recipe.time }} мин.</p>
                        </div>
                    </li>
                {% endif %}
            {% endfor %}
                <li class="card-user__item">
                    <a href="{% url 'profile' user_id=card.author.id %}" class="card-user__link link">{% if card.author.recipes.count > 3 %}Еще {{card.author.recipes.count}} рецептов...{% endif %}</a>
                </li>
        </ul>
    </div>
    <div class="card-user__footer">
        <button class="button button_style_light-blue button_size_auto" name="subscribe">Отписаться</button>
    </div>
</div>

recipes/templates/recipes/profile.html
{% extends 'base.html' %}
{% block title %}Рецепты{% endblock %}

{% block styles %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'pages/index.css' %}">
{% endblock %}

{% block content %}

        <div class="main__header">
            <h1 class="main__title">{% if author.get_full_name %}{{ author.get_full_name }} {% else %} {{ author.username }} {% endif %}</h1>
            {% include 'includes/tags.html' %}
        </div>
        {% if request.user.is_authenticated and request.user != author %}
        <div class="author-subscribe" data-author="{{ author.id }}">
            <p style="padding: 0 0 2em 0;">
                <button class="button button_style_light-blue button_size_auto" name="subscribe"{% if not is_subscribed %} data-out{% endif %}>{% if is_subscribed %}<span class="icon-check button__icon"></span>Отписаться от автора{% else %}Подписаться на автора{% endif %}</button>
            </p>
        </div>
        {% endif %}
        <div class="card-list">
            {% for card in page %}
                {% include 'recipes/recipe_cards.html' with card=card %}
            {% endfor %}
        </div>
    {% include 'includes/paginator.html' with page=page paginator=paginator %}
{% endblock %}

{% block javascript %}
    {% load static %}
        <script src="{% static 'js/components/MainCards.js' %}"></script>
        <script src="{% static 'js/components/Purchases.js' %}"></script>
        <script src="{% static 'js/components/Subscribe.js' %}"></script>
        <script src="{% static 'js/components/Favorites.js' %}"></script>
        <script src="{% static 'js/components/AuthorRecipe.js' %}"></script>
        <script src="{% static 'js/components/Header.js' %}"></script>
        <script src="{% static 'js/api/Api.js' %}"></script>
        <script src="{% static 'js/authorRecipe.js' %}"></script>
{% endblock %}

recipes/templates/recipes/purchases.html
{% extends 'base.html' %}
{% block title %}Список покупок{% endblock %}

{% block styles %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'pages/shopList.css' %}">
{% endblock %}

{% block content %}
{% csrf_token %}
{% load thumbnail %}
    <div class="main__header">
        <h1 class="main__title">Список покупок</h1>
    </div>
    <div class="card-list">
        <div class="card-list card-list_column">
        <ul class="shopping-list">
            {% for card in page %}
            <li class="shopping-list__item" data-id={{ card.id }}>
                <div class="recipe recipe_reverse">
                    {% thumbnail card.image "90x90" crop="center" upscale=True as im %}
                        <img src="{{ im.url }}" alt="{{ card.title }}" class="recipe__image recipe__image_big">
                    {% endthumbnail %}
                    <h3 class="recipe__title">{{ card.title }}</h3>
                    <p class="recipe__text"><span class="icon-time"></span> {{ card.time }} мин.</p>
                </div>
                <a href="#" class="shopping-list__button link">Удалить</a>
            </li>
            {% endfor %}
        </ul>
        <a href="{% url 'download_purchases' %}"><button class="button button_style_blue">Скачать список</button></a>
        </div>
    </div>
{% endblock %}

{% block javascript %}
    {% load static %}
    <script src="{% static 'js/config/config.js' %}"></script>
    <script src="{% static 'js/components/Header.js' %}"></script>
    <script src="{% static 'js/components/ShopList.js' %}"></script>
    <script src="{% static 'js/api/Api.js' %}"></script>
    <script src="{% static 'js/shopList.js' %}"></script>

{% endblock %}

recipes/templates/recipes/recipe_detail.html
{% extends 'base.html' %}
{% block title %}{{ recipe.title }}{% endblock %}

{% block styles %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'pages/single.css' %}">
{% endblock %}

{% block content %}
{% csrf_token %}
{% load thumbnail user_filters %}
    <div class="single-card" data-id="{{ recipe.id }}" data-author="{{ recipe.author.id }}">
        {% thumbnail recipe.image '480x480' crop="center" upscale=True as im %}
        <img src="{{ im.url }}" alt="recipe.name" width="480" height="480" class="single-card__image">
        {% endthumbnail %}
            <div class="single-card__info">
                <div class="single-card__header-info">
                    <h1 class="single-card__title">{{ recipe.title }}</h1>
                    {% if request.user.is_authenticated %}
                    <div class="single-card__favorite">
                        <button class="button button_style_none" name="favorites"{% if recipe not in favorites %} data-out{% endif %}><span class="icon-favorite icon-favorite_big{% if recipe in favorites %} icon-favorite_active{% endif %}"></span></button>
                        <div class="single-card__favorite-tooltip tooltip">Добавить в избранное</div>
                    </div>
                    {% endif %}
                </div>
                <ul class="single-card__items">
                    {% for tag in recipe.tags.all %}
                        <li class="single-card__item"><span class="badge badge_style_{{ tag|add_color }}">{{ tag.title }}</span></li>
                    {% endfor %}
                </ul>
                <div class="single-card__items single-card__items_column">
                    <p class="single-card__text"><span class="icon-time"></span> {{ recipe.time }} мин.</p>
                    <ul class="single-card__items">
                        <li class="single-card__item"><p class="single-card__text"><span class="icon-user"></span> {% if recipe.author.get_full_name %}{{ recipe.author.get_full_name }} {% else %} {{ recipe.author }} {% endif %}</p></li>
                        {% if request.user == recipe.author %}
                        <li class="single-card__item">  <a style="margin-left: 2.5em" href="{% url 'edit_recipe' recipe_id=recipe.id %}" class="single-card__text">Редактировать рецепт</a></li>
                        {% endif %}
                    </ul>
                </div>
                <ul class="single-card__items">
                    {% if request.user.is_authenticated %}
                        {% if recipe in purchase_list %}
                            <li class="single-card__item"> <button class="button button_style_light-blue-outline" name="purchases"><span class="icon-check button__icon"></span>Рецепт добавлен</button></li>
                        {% else %}
                            <li class="single-card__item"> <button class="button button_style_blue" name="purchases" data-out><span class="icon-plus"></span> Добавить в покупки</button></li>
                        {% endif %}
                    {% endif %}
                    {% if request.user.is_authenticated and request.user != recipe.author %}
                        <li class="single-card__item"> <button class="button button_style_light-blue button_size_auto" name="subscribe"{% if not is_subscribed %} data-out{% endif %}>{% if is_subscribed %}<span class="icon-check button__icon"></span>Отписаться от автора{% else %}Подписаться на автора{% endif %}</button> </li>
                    {% endif %}
                </ul>
                <div class="single-card__section">
                    <h3 class="single-card__section-title">Ингредиенты:</h3>
                    <div class="single-card__items single-card__items_column">
                        {% for ingredient in recipe.ingredient_set.all %}
                        <p class=" single-card__section-item">{{ ingredient.ingredient.title }} - {{ ingredient.amount }} {{ ingredient.ingredient.unit }}</p>
                        {% endfor %}
                    </div>
                </div>
                <div class="single-card__section">
                    <h3 class="single-card__section-title">Описание:</h3>
                    <p class=" single-card__section-text">{{ recipe.description }}</p>
                </div>
            </div>
        </div>
{% endblock %}

{% block javascript %}
    {% load static %}
    <script src="{% static 'js/components/Purchases.js' %}"></script>
    <script src="{% static 'js/components/Subscribe.js' %}"></script>
    <script src="{% static 'js/components/Favorites.js' %}"></script>

    <script src="{% static 'js/components/MainCards.js' %}"></script>
    <script src="{% static 'js/components/SingleCard.js' %}"></script>
    <script src="{% static 'js/components/Header.js' %}"></script>

    <script src="{% static 'js/api/Api.js' %}"></script>
    <script src="{% static 'js/singlePage.js' %}"></script>
{% endblock %}